name: 'Modify label'
description: 'Modify labels of an issue or pull request'
author: 'V0ldek (mat@gienieczko.com)'
inputs:
  action: # Whether to add or remove the label
    required: true
    description: 'Allowed values: add, remove'
  issue-number: # Number of the issue to modify
    required: true
    description: 'Number of the issue to modify'
  label-id: # ID of the label to add
    required: true
    description: 'ID of the label to add'
  token: # GitHub access token
    required: true
    description: 'GitHub access token'
runs:
  using: 'node16'
  main: 'dist/index.js'
