name: 'Add label'
description: 'Add a label to an issue or pull request'
author: 'V0ldek (mat@gienieczko.com)'
inputs:
  issue-number: # Number of the issue to modify
    required: true
    description: 'Number of the issue to modify'
  label-id: # ID of the label to add
    required: true
    description: 'ID of the label to add'
  token: # GitHub access token
    required: true
    description: 'GitHub access token'
runs:
  using: 'node16'
  main: 'dist/index.js'
